import { OfficesDataProps, PortfolioDataProps } from "../interface/redux/variable.interface"


export const portfolioData: PortfolioDataProps[] = [
  {
    id: 14,
    title: "Yukon App",
    desc: "Loyihaning asosiy maqsadi yuk va moshina egalariga kerakli bo'lgan elonlarni tez va qulay usulda topib berishdan iborat. Loyihaning web, telegram-bot va android dasturga ega sistema",
    src: "/images/yukon-app.png",
    owner: "Banerma Group",
    telegram: "t.me/yuk_uz_logistika_bot",
    hash: [
      "React Native",
      "React JS",
      "Google api",
      "Open AI",
      "GPT 4",
      "Tailwindcss",
      "Redux",
      "Redux Toolkit",
    ],
    position: "Full-stack Developer",
    url: {
      label: "Yukon App",
      href: "https://play.google.com/store/apps/details?id=yukon.uz.app&utm_source=portfolio-azamat",
    },
    start_date: "01/02/2025",
    final_date: "22/07/2025",
    status: true,
    manager: "Begzod Hayitboyev",
  },
  {
    id: 12,
    title: "JDM PRO",
    desc: "Saytda yaponiya moshinalarining elonlari joylashtiriladi...",
    src: "/images/jdm.png",
    owner: "Feruz Narziev",
    hash: ["nextjs", "typescript", "tailwindcss", "strapi.io"],
    position: "Full-stack Developer",
    url: {
      label: "JDM PRO",
      href: "https://jdm-pro.com?utm_source=portfolio-azamat",
    },
    start_date: "01/06/2025",
    final_date: "15/01/2025",
    status: true,
    manager: "Banerma Group",
  },
  {
    id: 13,
    title: "Yukon Uz",
    desc: "Loyihaning asosiy maqsadi yuk va moshina egalariga kerakli bo'lgan elonlarni telegram kanallardan tezda topib berishdan iborat...",
    src: "/images/yukon.png",
    owner: "Banerma Group",
    telegram: "t.me/yuk_uz_logistika_bot",
    hash: [
      "Ember js",
      "Ember Data",
      "Google api",
      "Open AI",
      "GPT 4",
      "Telegram Bot",
      "bootstrap",
      "Node Js",
      "Express Js",
      "Postgresql",
    ],
    position: "Full-stack Developer",
    url: {
      label: "Yukon Uz",
      href: "https://yukon.uz?utm_source=portfolio-azamat",
    },
    start_date: "01/09/2024",
    final_date: "01/06/2025",
    status: true,
    manager: "Begzod Hayitboyev",
  },
  {
    id: 10,
    title: "77kv",
    desc: "Loyiha realtor va agentlar uchun mo'ljallangan...",
    src: "/images/77kv.png",
    owner: "Banerma Group",
    hash: [
      "Ember js",
      "Ember Data",
      "Google api",
      "Open AI",
      "GPT 4",
      "Telegram integrate",
      "bootstrap",
      "Node Js",
      "Express Js",
      "Postgresql",
    ],
    position: "Full-stack Developer",
    url: {
      label: "77kv",
      href: "https://77kv.uz?utm_source=portfolio-azamat",
    },
    start_date: "01/12/2023",
    final_date: "01/06/2024",
    status: true,
    manager: "Begzod Hayitboyev",
  },
  {
    id: 11,
    title: "Market Lochin",
    desc: "Qurilish mollari do'koni uchun ichki sistema...",
    src: "/images/market-lochin.png",
    owner: "Shaxsiy loyiha",
    hash: [
      "Vite Js",
      "Redux",
      "Redux-toolkit",
      "tailwindcss",
      "material-tailwind",
    ],
    position: "Frontend Developer",
    url: {
      label: "Market Lochin",
      href: "https://marketlochin.uz?utm_source=portfolio-azamat",
    },
    start_date: "01/09/2023",
    final_date: "01/11/2023",
    status: true,
    manager: "Jamshid Kalandarov",
  },
  {
    id: 3,
    title: "Depository",
    desc: "Loyiha asosan majlislar va yig'ilishlarni online shaklda o'tkazishga xizmat qiladi...",
    src: "/images/depository.png",
    owner: "NAPA Automotive",
    hash: [
      "react-js",
      "redux",
      "socket.io",
      "bootstrap",
      "pwa",
      "zoom",
      "react-jutsu",
      "i18n",
    ],
    position: "Frontend Developer",
    url: {
      label: "Depository",
      href: "https://evote-uz.vercel.app",
    },
    start_date: "01/08/2021",
    final_date: "01/01/2022",
    status: false,
    manager: "Umid Abdusattorov",
  },
  {
    id: 9,
    title: "Topilmalar",
    desc: "Topilmalar axborot tizimi davlat markazlari uchun...",
    src: "/images/topilmalar.png",
    owner: "Davlat Xizmatlar Agentligi",
    hash: [
      "react-js",
      "redux",
      "redux-toolkit",
      "bootstrap",
      "crago",
      "eslint",
    ],
    position: "Frontend Developer",
    url: {
      label: "Topilmalar",
      href: "https://topilmalar.davxizmat.uz?utm_source=portfolio-azamat",
    },
    start_date: "01/02/2022",
    final_date: "01/01/2023",
    status: true,
    manager: "Mashrab Mamatqulov",
  },
  {
    id: 1,
    title: "Smart Adliya",
    desc: "Adliya Vazirligining integratsiya platformasi...",
    src: "/images/smart-adliya.png",
    owner: "Adliya Vazirligi",
    hash: ["java", "oop", "spring", "springboot", "mail"],
    position: "Backend Developer",
    url: {
      label: "Smart Adliya",
      href: "https://smart.adliya.uz?utm_source=portfolio-azamat",
    },
    start_date: "01/05/2022",
    final_date: "01/12/2022",
    manager: "Kamoliddin Xojayev",
    status: true,
  },
  {
    id: 2,
    title: "B-Advice",
    desc: "Tadbirkorlar uchun maslahat platformasi...",
    src: "/images/b-advice.png",
    owner: "Adliya Vazirligi",
    hash: ["java", "oop", "spring", "springboot", "microservice", "mail"],
    position: "Backend Developer",
    url: {
      label: "B-Advice",
      href: "https://b-advice.uz?utm_source=portfolio-azamat",
    },
    start_date: "01/07/2022",
    final_date: "01/12/2022",
    status: true,
    manager: "Kamoliddin Xojayev",
  },
  {
    id: 5,
    title: "EximERP",
    desc: "Deklaratsiya va import jarayonlarini avtomatlashtiruvchi platforma...",
    src: "/images/eximerp.jpg",
    owner: "Kervanyul Technologies",
    hash: [
      "react-js",
      "vite-js",
      "redux",
      "redux-toolkit",
      "socket.io",
      "material-ui",
      "i18n",
      "one-id",
    ],
    position: "Texnik yordamchi - Frontend",
    url: {
      label: "EximERP",
      href: "https://eximerp.uz?utm_source=portfolio-azamat",
    },
    start_date: "01/06/2023",
    final_date: "01/09/2023",
    status: true,
    manager: "Bexruz Muzaffarov",
  },
];

export const officeData: OfficesDataProps[] = [
    {
        id: 1,
        title: "Napa Automotive",
        desc: "",
        src: "https://it-market.uz/media-django/__sized__/logos/Logo_NAPA_Automotive-thumbnail-128x128-90.jpeg",
        owner: "Umid Abdusattorov"
    },
    {
        id: 2,
        title: "Davlat Xizmatlar Agentligi",
        desc: "",
        owner: "",
        src: "https://static8.tgstat.ru/channels/_0/e0/e06c9abc54703ce47dbf2eb40538a46d.jpg"
    },
    {
        id: 3,
        title: "Adliya Vazirligi (AKTRM)",
        desc: "",
        src: "https://huquqiyportal.uz/_nuxt/img/adliya-logo.c5f976c.png",
        owner: ""
    },
    {
        id: 4,
        title: "Kervanyol technologies",
        desc: "",
        src: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQDN56czZUUpMzgW4KrIGHOmRUJRJ3dZYfFhA&s",
        owner: "",
    },
    {
        id: 5,
        title: "Banerma",
        desc: "",
        owner: "Begzod Hayitboyev",
        src: '/images/big-tech.png'
    }
]
